include: add missing interact.h to installed headers
Without this, including <ecoli.h> after installing in /usr/include
causes an error:

/usr/include/ecoli.h:14:10: fatal error: ecoli/interact.h: No such file or directory
   14 | #include <ecoli/interact.h>
      |          ^~~~~~~~~~~~~~~~~~

Fixes: bc90312a4285 ("editline: split in 2 files")
Signed-off-by: Robin Jarry <rjarry@redhat.com>